# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# File Options
files:
  include: 'app/styles/**/*.s+(a|c)ss'
# Rule Configuration
rules:
  # Extends
  extends-before-declarations: 2
  extends-before-mixins: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    -
      exclude:
        # To allow for fallbacks
        # TODO(Maddie): eventually get rid of these
        - background
        - border
  no-empty-rulesets: 2
  no-ids: 2
  no-invalid-hex: 2
  no-misspelled-properties:
    - 2
    -
      'extra-properties':
        - 'border-'
        - 'margin-'
        - 'osx-font-smoothing'
  no-mergeable-selectors: 1
  no-trailing-whitespace: 2
  no-url-protocols: 2
  no-warn: 2

  # Nesting
  nesting-depth: 1

  # Name Formats
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      ignore:
        # These are being ignored because the DOM elements are pulled in via
        # CKEditor and we cannot control the class names
        - 'cke_tabulation'
        - 'cke_editable'
  function-name-format: 2
  mixin-name-format: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false

  # Style Guide
  border-zero:
    - 1
    -
      convention: 'none'
  brace-style: 1
  clean-import-paths: 1
  empty-args:
    - 1
    -
      include: true
  hex-length:
    - 1
    -
      style: long
  hex-notation: 1
  indentation: 2
  leading-zero:
    - 1
    -
      include: true
  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  zero-unit: 1

  # Inner Spacing
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-bang: 1
  space-before-brace: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
